server:
  port: 8090
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.46.211.213:3306/chinasoft
    username: root
    password: zhongruanguoji

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
