server:
  port: 8090
spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${sql.url}
    username: ${sql.username}
    password: ${sql.password}


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
